import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Cabecalho from "./components/Cabecalho";
import Rodape from "./components/Rodape";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Cabecalho/>

        <div className="flex flex-col min-h-screen">
          <main className="flex-grow">
            {children}
          </main>
         <Rodape />
        </div>
        
      </body>
    </html>
  );
}
